spring:
    datasource:
        jdbcUrl: jdbc:postgresql://localhost:5432/sisyphus
        username: postgres
        password: 123456
    jpa:
        ddl-auto: update
        show-sql: true
        hibernate:
            format_sql: true
            use_sql_comments: true
            default_batch_fetch_size: 100
            jdbc.batch_size: 100
            order_inserts: true
            order_updates: true
            jdbc.time_zone: UTC
    liquibase:
        change-log: classpath:db/changelog/changelog.xml

server:
    port: 3000

logging:
    level:
        web: info